### PR TITLE
line_length BUG

### PR DESCRIPTION
**Pull request by lnksz**
It is a little bug causing big problems.
See: [Bug Gist](https://gist.github.com/lnksz/e1ab0e78c98cb85dbc3d66adfcaa99d2)

### CODE REVIEW

**Comment by ojdo** [comment]
Ok, having realised that this PR is actually a superset of the previous one, I can already state a wish: please break this HUUUUGE pull request up into thematically grouped changes that can be reviewed and merged one by one. Ideas for independent PRs:

### Small ones

 - Documentation fixes
 - Better `.gitignore`

### Medium PRs

 - Improved gridder functionality
 - Prerun with `cpu_count` functionality. (I don't like the default of exhausting all cores.)

### Large PRs

 - New plot function
 - Switching to plotly

Don't understand me wrong: most code looks pretty good, but this PR is much too huge. I had made an exception for the refactoring effort, but now that rivus is split into modules, development should happen in digestible chunks, not large buffets.

@tum-ens/members : of couse, if anybody of you has another opinion, feel free to merge. I just offer my 2ct here :-)

**Comment by lnksz** [comment]
Ops, sorry those commits were ment as separate PRs, I will split them up.

**Comment by lnksz** [comment]
Threads count: I've set it *down* to the max number of cpus, as before (copied from haag15 project) was hard-coded 48... (I suppose because of server computation)
I read up  [gurobi Threads](https://www.gurobi.com/documentation/7.0/refman/threads.html) and so this setting may be surplus in normal use because:

>  The default value of 0 is an automatic setting. It will generally use all of the cores in the machine, but it  may choose to use fewer.
> 
> While you will generally get the best performance by using all available cores in your machine, there are a few exceptions. One is of course when you are sharing a machine with other jobs. In this case, you should select a thread count that doesn't oversubscribe the machine.

But I will refactor these accumulated commits into topic based PRs, so we can discuss seperately about acceptance/rejection regarding specific changes.

**Comment by ojdo** [comment]
Yes, you are right in that the *original* code quality was not stellar to begin with, esp. when compared  with the much more stream-lined urbs code. So thank you very much not only for the contributions but also for the willingness to clean/split them for my reviewing "pleasure"... :blush:

**Comment by lnksz** [comment]
My pleasure ;) It is a good opportunity to practice some Git-Jitsu...

**Comment by lnksz** [comment]
This could be closed, as I have split up the majority of the contents.
The title giving bug is now in PR #13

**Pull request closed without merging**
