### PR TITLE
BUGFIX for line_length()

### PR DESCRIPTION
**Pull request by lnksz**
It is a little bug causing big problems.
See: [Detailed Bug Description and Analysis](https://gist.github.com/lnksz/e1ab0e78c98cb85dbc3d66adfcaa99d2)

### CODE REVIEW

**Comment by lnksz** [comment]
Although I analyzed this code relatively throughout in the context of `rivus`, it is still hard to believe that this bug went on unnoticed through your work @ojdo.
I commented out your original code just in case that you took care of the problem somehow when you used _rivus and urbs_ iteratively. (shapefile attributes?)
(But if one uses only rivus, I dare say, the effect is quite nasty)

**Comment by ojdo** [comment]
I'll have a thorough look at this one - at first glance it indeed looks pretty embarrassing. I will come back to this probably only next weekend, as the coming work week will be pretty busy.

**Comment by ojdo** [comment]
State: I'm almost done. What's left is that I check your proposed solution. The hard-coded index switching, especially with the negative `[-1]` has the smell of work-around, and not being the "idiomatic" way to flunch the two packages shapely and geopy together. I hope I can come up with something more "semantic" like - pseudo-code ahead - 

```python
sum(geopy.distance(swap(a), swap(b)).meters 
    for (a, b) in pairs(line.coords)))
```
My expectation would be that one of the packages already provides such a `swap` feature in one form or another:
 * geopy/geopy#202 speaks of the issue, but there's no solution without a maintainer in sight.
 * Maybe a switch to [Geographiclib](https://gis.stackexchange.com/a/184413/19627) might be in order.
 * Or, if one switches to GeoDataFrames for the input data, the real solution could look rather like this: 
```python
edge = read_file('edge.shp')
edge_projected = edge.to_crs('local_projected_crs')
edge['length'] = edge_projected.length
```

Note to self: I was so nice to post my erroneous function also [on gis.stackexchange.com](https://gis.stackexchange.com/a/115285/19627). Once I have a clean fix, I will have to update the solution there as well.

**Comment by lnksz** [comment]
Hi,

Just a note, now as far as discovered, the rivus.py intern logoc is that
everything (georelated) is in WGS84 crs and no specific espg code is
handled.
On the one hand, it is very consistent and "spells after conformity" as
WGS84 the most well-known CRS is.
On the other hand, the throughout used shapely package (which is also the
core of geopandas) was built with projected coordinate systems in mind. So
I think the decision to depend on an espg code or note is rather project
wide. (But also includes the ability to use e. g. GeoSeries.length
properly, or in other words leverage the hidden potential in the shapely
based geometrly column)

As I looked earlier into this espg question, I think I came across a
package that determines the correct espg from LatLon. That could ease the
data input for future users. I will have a look at it on this week.

(sorry for pure text and typos, this was written on a phone)

**Comment by ojdo** [comment]
Yes, after long headaches of handling projection within dhmin, I tried to make rivus as CRS-agnostic as possible. A possible route for a fully automatic projection solution could look like this:

1. Determine bounding box of project area (min and max of lat and lon).
2. [Calculate the appropriate UTM zone](https://stackoverflow.com/questions/9186496/determining-utm-zone-to-convert-from-longitude-latitude) for both longitudes (min and max). Background: the [Universal Transverse Mercator](https://en.wikipedia.org/wiki/Universal_Transverse_Mercator_coordinate_system) is *the* go-to projection for projected coordinates, just like WGS84 is *the* go-to ellipsoid for geographic coordinates. If you want/need to use a different projection, you usually know *why* you want to. For deciding between N (north) and S (south), just look at the signs of latitude.
3. If both zones match, the project area typcially has the expected size. Possible edge cases: minimum and maximum coordinates lie in different zones. In that case (or always, to simplify logic), let the project area centroid be the arbiter. In that case, emit a warning if the bbox indicates a too large project area.
4. Convert the UTM zone number (e.g. [19S](http://www.spatialreference.org/ref/epsg/32719/) or [32N](http://spatialreference.org/ref/epsg/32632/)) to an epsg code using this advanced formula:

```
N: EPSG:326<number>, e.g. EPSG:32632 for 32N
S: EPSG:327<number>, e.g. EPSG:32719 for 19S
```

5. Use `to_crs` as before to calculate projected lengths using only GeoPandas facilities.

All that hassle just for a simple length(some_line). That's why I liked (and still like) the geopy solution when I found it.

I will throw some more time at the topic later this week. Perhaps it's best to stick with a direct geodesic calculation. The above still seems to me to be a rather ugly work-around for an otherwise "simple" problem.

**Comment by lnksz** [comment]
I rather share your opinion on the overhead and generally like the
maintained geopy package.

My suggested work around was a quick hotfix to test with the correct
length.
If there is no swap in the other libraries, we can push the swap logic one
layer deeper to aid the readability of the code, but in the end a swap
stays a swap. :)

**Comment by lnksz** [comment]
For future integration: OSMnx

Package [OSMnx] could be investigated, as it proposes a very convenient `gdf_from_place` function.  
(Although it fetches one polygon, the source could serve as a good example. Alternatively, the whole shapefile phase could be skipped, with its ox.graph\_from\_place('Manhattan, New York, USA', network\_type='drive') function. And the edge could be calculated from that source. 

There are even some possibilities to **simplify the resulting graph,** which could be an alternative to the current `skeletron` based approach.

Furthermore, this package already **solved the automated UTM code calculation** so at least, that would be of great use for us. :

    >>> osmnx as ox
    >>> city = ox.gdf_from_place('Berkeley, CA')
    >>> city_xy = os.project_gdf(city)
    >>> G = ox.graph_from_place('Manhattan, New York, USA', network_type='drive'

  [OSMnx]: https://github.com/gboeing/osmnx

**Comment by ojdo** [comment]
Wow, the OSMnx package looks nice. Could you convert your last comment to a simple Feature request issue? That way, it's content remains visible for future contributors.

**Pull request merged**
